services:
    shameme_app:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        container_name: shameme-app
        env_file:
            - ./.env
        volumes:
            - "./frontend:/frontend"
            - "/frontend/.next"
            - "/frontend/node_modules"
        expose:
            - '3000'
        ports:
            - '3000:3000'
        command: npm run start