services:
  shameme_app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    container_name: shameme-app
    volumes:
      - "./:/app"
     # - "/app/node_modules"  # Uncomment if necessary
    ports:
      - "${APP_PORT}:3000"
    command: "npm run dev"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    container_name: shameme-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - shameme_db:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: shameme-phpmyadmin
    env_file:
      - .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db

volumes:
  shameme_db:
